In [4]:
# Importing the most important library numpy
# Numpy is preffered over python lists since most of its implementations are faster (the functions are tied closer with hardware)
import numpy as np

### Run the following to grasp the basics of numpy

In [5]:
# 1D array
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Array of zeros
zeros = np.zeros((2, 3))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((3, 2))
print("Ones Array:\n", ones)

# Array with a range of values
range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)

# Array with equally spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_arr)

# Random array
random_arr = np.random.rand(3, 3)  # Uniform distribution
print("Random Array:\n", random_arr)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Random Array:
 [[0.51066512 0.47966806 0.07141363]
 [0.52878573 0.35998476 0.05227954]
 [0.21364864 0.31341686 0.06701179]]


In [6]:
# In a numpy array, all the elements must be homogenous (of the same data type)
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # Dimensions
print("Size:", arr.size)  # Total number of elements
print("Data Type:", arr.dtype)  # Type of elements
print("Number of Dimensions:", arr.ndim)  # Number of dimensions

Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, Column 1

# Slicing
print("First row:", arr[0, :])  # All columns of the first row
print("First column:", arr[:, 0])  # All rows of the first column
print("Subarray:\n", arr[0:2, 1:3])  # Rows 0-1 and Columns 1-2

Element at [0, 1]: 2
First row: [1 2 3]
First column: [1 4]
Subarray:
 [[2 3]
 [5 6]]


In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

# Broadcasting
scalar = 2
print("Multiply by scalar:", arr1 * scalar)

# Mathematical functions
print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Multiply by scalar: [2 4 6]
Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape
reshaped = arr.reshape((3, 2))
print("Reshaped Array:\n", reshaped)

# Transpose
transposed = arr.T
print("Transposed Array:\n", transposed)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking
stacked = np.vstack((arr1, arr2))  # Vertical stack
print("Stacked Vertically:\n", stacked)

hstacked = np.hstack((arr1, arr2))  # Horizontal stack
print("Stacked Horizontally:", hstacked)

# Splitting
split = np.split(arr2, 3)  # Split into 3 parts
print("Split Array:", split)

Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally: [1 2 3 4 5 6]
Split Array: [array([4]), array([5]), array([6])]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean indexing
even = arr[arr % 2 == 0]
print("Even Numbers:", even)
# Masking is a common technique used
print("Masking:", arr % 2 == 0)

# Filtering
filtered = arr[arr > 3]
print("Numbers greater than 3:", filtered)

Even Numbers: [2 4 6]
Masking: [False  True False  True False  True]
Numbers greater than 3: [4 5 6]


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Standard Deviation: 1.707825127659933


### Some assignment problems

In [13]:
# Assignment 1
'''
Create an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.
Then reshape it to a (9, 2) array and take its transpose. 
Find the locations where all elements are greater than the mean of the array and print it
'''

'\nCreate an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.\nThen reshape it to a (9, 2) array and take its transpose. \nFind the locations where all elements are greater than the mean of the array and print it\n'

In [14]:

arr = np.random.rand(3, 6)
print("Original Array:")
print(arr)

v1 = np.array([0, 0, 2, 4, 5, 3])
stacked = np.vstack((v1, v1, v1))
arr = arr + stacked
print("Array after adding [0, 0, 2, 4, 5, 3] to each row:")
print(arr)

arr = arr.reshape(9, 2)
print("Reshaped Array (9, 2):")
print(arr)

arr_transposed = arr.T
print("Transposed Array:")
print(arr_transposed)

mean = np.mean(arr_transposed)
print(f"Mean of the array: {mean:.2f}")
greater_than_mean = np.where(arr_transposed > mean)
print("Locations where elements are greater than the mean:")
print(greater_than_mean)


Original Array:
[[0.73571904 0.62145357 0.99698276 0.53135144 0.35659324 0.62606592]
 [0.180326   0.56444848 0.59403102 0.77577001 0.85110088 0.15201141]
 [0.85972614 0.40352646 0.5802815  0.99518248 0.92001246 0.55006273]]
Array after adding [0, 0, 2, 4, 5, 3] to each row:
[[0.73571904 0.62145357 2.99698276 4.53135144 5.35659324 3.62606592]
 [0.180326   0.56444848 2.59403102 4.77577001 5.85110088 3.15201141]
 [0.85972614 0.40352646 2.5802815  4.99518248 5.92001246 3.55006273]]
Reshaped Array (9, 2):
[[0.73571904 0.62145357]
 [2.99698276 4.53135144]
 [5.35659324 3.62606592]
 [0.180326   0.56444848]
 [2.59403102 4.77577001]
 [5.85110088 3.15201141]
 [0.85972614 0.40352646]
 [2.5802815  4.99518248]
 [5.92001246 3.55006273]]
Transposed Array:
[[0.73571904 2.99698276 5.35659324 0.180326   2.59403102 5.85110088
  0.85972614 2.5802815  5.92001246]
 [0.62145357 4.53135144 3.62606592 0.56444848 4.77577001 3.15201141
  0.40352646 4.99518248 3.55006273]]
Mean of the array: 2.96
Locations where e

In [15]:
# Assignment 2
'''
Create an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation
(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)
'''

'\nCreate an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation\n(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)\n'

In [17]:

arr = np.random.poisson(lam=5, size=20)
print("Original Poisson Array:")
print(arr)

mean = np.mean(arr)
std_dev = np.std(arr)

arr = (arr - mean) / std_dev

print(arr)


Original Poisson Array:
[ 1  6  2  4  4  8  1  4  3  1  8  4  3  4  3  2 11  1  8  7]
[-1.16462023  0.6271032  -0.80627555 -0.08958617 -0.08958617  1.34379258
 -1.16462023 -0.08958617 -0.44793086 -1.16462023  1.34379258 -0.08958617
 -0.44793086 -0.08958617 -0.44793086 -0.80627555  2.41882664 -1.16462023
  1.34379258  0.98544789]
